# Only run for PRs and master
trigger:
- main

pr:
- main

variables:
  xcodeApp: /Applications/Xcode_11.5.app
  repoName: fasmat/homebrew-trader-workstation

pool:
  vmImage: 'macOS-10.15'

jobs:
- job: Formula_CI
  steps:
  - script: sudo xcode-select -s $(xcodeApp)/Contents/Developer
    displayName: xcode-select
  - script: |
      brew update-reset "$(brew --repository)"
      HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/$(repoName)"
      mkdir -p "$HOMEBREW_TAP_DIR"
      rm -rf "$HOMEBREW_TAP_DIR"
      ln -s "$PWD" "$HOMEBREW_TAP_DIR"
    displayName: setup tap
  - script: |
      brew install --cask trader-workstation-latest
      brew uninstall --cask trader-workstation-latest
    displayName: brew install and uninstall trader-workstation latest
  - script: |
      brew install --cask trader-workstation-beta
      brew uninstall --cask trader-workstation-beta
    displayName: brew install and uninstall trader-workstation beta
  - script: |
      brew install --cask trader-workstation
      brew uninstall --cask trader-workstation
    displayName: brew install and uninstall trader-workstation
