name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13]

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Cache Homebrew Gems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - name: Install Homebrew Gems
        id: gems
        run: brew install-bundler-gems
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Trader workstation (stable)
        run: |
          brew style --cask trader-workstation-stable
          brew audit --cask --online --strict trader-workstation-stable

          brew install --cask trader-workstation-stable
          brew uninstall --cask trader-workstation-stable

      - name: Trader workstation (latest)
        run: |
          brew style --cask trader-workstation-latest
          brew audit --cask --online --strict trader-workstation-latest

          brew install --cask trader-workstation-latest
          brew uninstall --cask trader-workstation-latest

      - name: Trader workstation (beta)
        run: |
          brew style --cask trader-workstation-beta
          brew audit --cask --online --strict trader-workstation-beta

          brew install --cask trader-workstation-beta
          brew uninstall --cask trader-workstation-beta

      - name: IBKR Desktop
        run: |
          brew style --cask ibkr-desktop-latest
          brew audit --cask --strict ibkr-desktop-latest

          brew install --cask ibkr-desktop-latest
          brew uninstall --cask ibkr-desktop-latest
