name: GitHub Actions CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup trader workstation tap
        run: |
          brew update-reset "$(brew --repository)"
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/${{ github.repository }}"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"

          echo "homebrew tap dir: $HOMEBREW_TAP_DIR"
          echo "pwd: $PWD"

          ln -s "$PWD" "$HOMEBREW_TAP_DIR"

      - name: Trader workstation (stable)
        run: |
          brew install --cask trader-workstation
          brew uninstall --cask trader-workstation

      - name: Trader workstation (latest)
        run: |
          brew install --cask trader-workstation-latest
          brew uninstall --cask trader-workstation-latest

      - name: Trader workstation (beta)
        run: |
          brew install --cask trader-workstation-beta
          brew uninstall --cask trader-workstation-beta
